### ISSUE TITLE
validate checking is wrong

### ISSUE THREAD

**Issue by rom1504** [pqml/prismarine-tokens#2]
https://github.com/pqml/prismarine-tokens/blob/master/libs/tokens-use.js#L86

see https://github.com/PrismarineJS/node-minecraft-protocol/blob/5126b969546dbfb38aaaa61ab2f92d08476659e8/src/client/caseCorrect.js#L25

**Comment by pqml** [comment]
Yep ! I need to refactor all the code of this repo when I have a bit of time. 

I think the validate function used to return "success" as first parameter when I did this (For instance see https://github.com/zekesonxx/node-yggdrasil/blob/b93e1a347665d0b1bca5079762e149badb534b50/lib/index.js#L92)
